version: '2'
services:
    dreadflicks-app:
        image: dreadflicks
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dreadflicks-postgresql:5432/dreadflicks
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=dreadflicks-elasticsearch:9300
        ports:
            - 8080:8080
    dreadflicks-postgresql:
        extends:
            file: postgresql.yml
            service: dreadflicks-postgresql
    dreadflicks-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: dreadflicks-elasticsearch
